export { default as About } from "./about/about";
export { default as Bio } from "./bio/bio";
export { default as Contact } from "./contact/contact";
export { default as Services } from "./services/services";
export { default as Reviews } from "./reviews/reviews";
export { default as Header } from "./header/header";
export { default as Footer } from "./footer/footer";
export { default as Terms } from "./terms/terms";
export { default as Privacy } from "./privacy/privacy-policy";
